joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: haircutterbot/cmd_vel
      axis_mappings:
        linear-x:
          axis: 1
          scale: 0.5
          offset: -0.03
        angular-z:
          axis: 0
          scale: 0.5
          offset: 0
        linear-y:
          axis: 2
          scale: 0.3
          offset: 0
        linear-z:
          button: 2
          scale: 3.0